### ISSUE TITLE
Generate class-level mutants through muScript (command line)

### ISSUE THREAD

**Issue by leofernandesmo** [jeffoffutt/muJava#7]
Hi, I'm doing a research on equivalent mutants and would like to use MuJava as one of the tools to evaluate. So, would be great if it was able to generate class level mutants.
Is it difficult?

**Comment by DerBaer0** [comment]
Hi, I had the same problem when I did some research on .. guess what .. equivalent mutants.
I maybe you can checkout this commit on my fork of muJava. I used this one and it worked well for me. Yet I'm not sure if I implemented all features for class mutants and it is not the cleanest solution.

https://github.com/DerBaer0/muJava/commit/20e4618c2a5f391ef9f2e84c2a35c5bf89226f8f

**Comment by leofernandesmo** [comment]
Thank you @DerBaer0 ,
It generated some class level mutants using -ALLALL option. I didn't check if all possible class mutations were generated...
It's a very important feature that could be in the original repository. Did you open a pool request?

**Comment by leofernandesmo** [comment]
Hi @DerBaer0 ,
I found a bug :( ... 
When the Java file in src/ folder contains no package structure, it works fine, but if I have any package declaration in code the program (@DerBaer0 mujava fork) can generate mutants and print:

```
5 : test5
 -- Can't apply because class not found
```
Where test5 is a package (eg.: test5.Package_0.ClassId_0.java)

I will try fix it...but if you have any idea, let me know.

**Comment by DerBaer0** [comment]
Thanks for the hint @leofernandesmo 
I can't say anything to this at the moment, sorry. But if you can't fix it fast, I can look into this the next days. Did you merge my commit into this main repo or used it without the recent changes here? Packages were not well supported during the time of my fork. 

.. I did a lot of changes to the code, but didn't create pull request because the repository seemed dead during this time and my first request is ignored. But maybe I should take some time, commit the stuff and file some pull request. But this will take several days because it diverged quite a lot.

**Comment by leofernandesmo** [comment]
Hi @DerBaer0 ,
No I didn't merge to main repo. I just used your forked version.
I'll merge and response here.

Thanks again.

**Comment by leofernandesmo** [comment]
Hi @DerBaer0 ,
I tried to merge but, I couldn't fix it. :( 
Please, if you can check this problem and fix. It would be very important to me.

Thanks again,
